import Footer from "@/componets/layout/Footer"
import "./globals.css"
import "./responsive.css"
import Header from "@/componets/layout/Header"
import { SliderProvider } from "@/context/SliderContext"
import { SeasonProvider } from "@/context/SeasonContext"
import ProgressBar from "@/packages/ProgressBar"
import { SearchProvider } from "@/context/SearchContext"
export const metadata = {
  title: "فیلم و سریال",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
        />
      </head>
      <body suppressHydrationWarning={true}>
        <SliderProvider>
          <SeasonProvider>
            <SearchProvider>
              <ProgressBar
                height="2px"
                color="#ffc400"
                options={{ showSpinner: false }}
              />
              <Header />
              {children}
              <Footer />
            </SearchProvider>
          </SeasonProvider>
        </SliderProvider>
      </body>
    </html>
  )
}
